[build]
  command = "bash netlify.sh"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# API routes for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

# Function bundle settings
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# For local development with Netlify Dev
[dev.functions]
  directory = "netlify/functions"
