[build]
  base = "" # Use root of repo
  command = "npm run build"
  publish = "client/dist/public"

[build.environment]
  SUPABASE_URL = "https://pqfsbxcbsxuyfgqrxdob.supabase.co"
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZnNieGNic3h1eWZncXJ4ZG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzAxNzAsImV4cCI6MjA1NzkwNjE3MH0.1bjMIO2hzyCJS1ExpsB1JsCmkH8D2d2M_-Psz2DDJrQ"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZnNieGNic3h1eWZncXJ4ZG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzAxNzAsImV4cCI6MjA1NzkwNjE3MH0.1bjMIO2hzyCJS1ExpsB1JsCmkH8D2d2M_-Psz2DDJrQ"
  NODE_VERSION = "22"
  
[[redirects]]
  from = "/eclipse"
  to = "/eclipse/index.html"
  status = 200

[[redirects]]
  from = "/marketing"
  to = "/marketing/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
